### ISSUE TITLE
re-numbering frames

### ISSUE THREAD

**Issue by jcguu95** [szos/stumpwm-dwm-tiling#6]
First of, thanks for doing all this. I also believe that `stumpwm` is in need a dynamical tiling framework.

May I suggest one thing? I haven't looked into the very internal of this repo, but it seems to me that things will be much easier if we re-number the frames. That is to say, the master frame should always be of number 0, and so on:

```
---------------
|         | 1 |
|    0    | 2 |
|         | 3 |
---------------
```

It is easier for the user to select, for example. It would also make it easier to solve the cycling problem that's currently presented in `readme`.

If you feel like this changes the internal of `stumpwm` too much, we can also create our own numbering too. But we might have to rewrite our own `choose-frame-by-number`.

Please let me know what you think! Thanks again.

**Comment by szos** [comment]
Hi jcguu95! 

This repo isnt really relevant any longer, and there is currently a PR open with StumpWM to add this functionality in. The code has changed a fair bit, and been simplified in places. Your suggestion of the master frame always being frame 0 is actually implemented there. Id love to get some feedback on the PR, and I left a comment there describing what I think needs discussing. I have two forks of StumpWM dedicated to this, one of which goes further than just adding dynamic tiling, but also changes the group class hierarchy a bit in order to make things fit better with multiple group types. The PR is here: https://github.com/stumpwm/stumpwm/pull/851, and I'll add to the readme of this repo that this repo is no longer relevant.

**Comment by jcguu95** [comment]
Got it! Thanks.
